name: Test compile in Alpine
on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compiles source

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Compile
        run: jjmerelo/alpine-moarvm-testbed@master
